#!/bin/bash
echo "Post install script is running now"
geo=$(xrandr | awk '/\*/ {split($1, res, "x"); resX=res[1]-100; resY=res[2]-100; if (resY > 880) resY=880; printf("%dx%d+50+10\n", resX, resY); exit}')
desktop_file="/usr/share/applications/spotify-tui.desktop"
sed -i "s|^Exec=.*|Exec=konsole -T spotify-tui --nomenubar --notabbar --noscrollbar --miniicon spt --caption \"\" --icon spt --geometry $geo -e spt|" "$desktop_file"
echo "Done."
